//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  profile: Profile;
  profileConnection: ProfileConnection;
  experience: Experience;
  experienceConnection: ExperienceConnection;
  education: Education;
  educationConnection: EducationConnection;
  skill: Skill;
  skillConnection: SkillConnection;
  hobby: Hobby;
  hobbyConnection: HobbyConnection;
  declaration: Declaration;
  declarationConnection: DeclarationConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProfileArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProfileConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProfileFilter>;
};


export type QueryExperienceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryExperienceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ExperienceFilter>;
};


export type QueryEducationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEducationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EducationFilter>;
};


export type QuerySkillArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySkillConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SkillFilter>;
};


export type QueryHobbyArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHobbyConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HobbyFilter>;
};


export type QueryDeclarationArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDeclarationConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DeclarationFilter>;
};

export type DocumentFilter = {
  profile?: InputMaybe<ProfileFilter>;
  experience?: InputMaybe<ExperienceFilter>;
  education?: InputMaybe<EducationFilter>;
  skill?: InputMaybe<SkillFilter>;
  hobby?: InputMaybe<HobbyFilter>;
  declaration?: InputMaybe<DeclarationFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Profile | Experience | Education | Skill | Hobby | Declaration | Folder;

export type Profile = Node & Document & {
  __typename?: 'Profile';
  name: Scalars['String']['output'];
  role: Scalars['String']['output'];
  summary?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ProfileFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
};

export type ProfileConnectionEdges = {
  __typename?: 'ProfileConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Profile>;
};

export type ProfileConnection = Connection & {
  __typename?: 'ProfileConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProfileConnectionEdges>>>;
};

export type Experience = Node & Document & {
  __typename?: 'Experience';
  role: Scalars['String']['output'];
  company: Scalars['String']['output'];
  duration?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ExperienceFilter = {
  role?: InputMaybe<StringFilter>;
  company?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type ExperienceConnectionEdges = {
  __typename?: 'ExperienceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Experience>;
};

export type ExperienceConnection = Connection & {
  __typename?: 'ExperienceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ExperienceConnectionEdges>>>;
};

export type Education = Node & Document & {
  __typename?: 'Education';
  degree: Scalars['String']['output'];
  institution: Scalars['String']['output'];
  status?: Maybe<Scalars['String']['output']>;
  year?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type EducationFilter = {
  degree?: InputMaybe<StringFilter>;
  institution?: InputMaybe<StringFilter>;
  status?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type EducationConnectionEdges = {
  __typename?: 'EducationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Education>;
};

export type EducationConnection = Connection & {
  __typename?: 'EducationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EducationConnectionEdges>>>;
};

export type Skill = Node & Document & {
  __typename?: 'Skill';
  title: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SkillFilter = {
  title?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
};

export type SkillConnectionEdges = {
  __typename?: 'SkillConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Skill>;
};

export type SkillConnection = Connection & {
  __typename?: 'SkillConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SkillConnectionEdges>>>;
};

export type Hobby = Node & Document & {
  __typename?: 'Hobby';
  name: Scalars['String']['output'];
  icon?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HobbyFilter = {
  name?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
};

export type HobbyConnectionEdges = {
  __typename?: 'HobbyConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Hobby>;
};

export type HobbyConnection = Connection & {
  __typename?: 'HobbyConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HobbyConnectionEdges>>>;
};

export type Declaration = Node & Document & {
  __typename?: 'Declaration';
  statement?: Maybe<Scalars['String']['output']>;
  name?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type DeclarationFilter = {
  statement?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
};

export type DeclarationConnectionEdges = {
  __typename?: 'DeclarationConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Declaration>;
};

export type DeclarationConnection = Connection & {
  __typename?: 'DeclarationConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DeclarationConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateProfile: Profile;
  createProfile: Profile;
  updateExperience: Experience;
  createExperience: Experience;
  updateEducation: Education;
  createEducation: Education;
  updateSkill: Skill;
  createSkill: Skill;
  updateHobby: Hobby;
  createHobby: Hobby;
  updateDeclaration: Declaration;
  createDeclaration: Declaration;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateProfileArgs = {
  relativePath: Scalars['String']['input'];
  params: ProfileMutation;
};


export type MutationCreateProfileArgs = {
  relativePath: Scalars['String']['input'];
  params: ProfileMutation;
};


export type MutationUpdateExperienceArgs = {
  relativePath: Scalars['String']['input'];
  params: ExperienceMutation;
};


export type MutationCreateExperienceArgs = {
  relativePath: Scalars['String']['input'];
  params: ExperienceMutation;
};


export type MutationUpdateEducationArgs = {
  relativePath: Scalars['String']['input'];
  params: EducationMutation;
};


export type MutationCreateEducationArgs = {
  relativePath: Scalars['String']['input'];
  params: EducationMutation;
};


export type MutationUpdateSkillArgs = {
  relativePath: Scalars['String']['input'];
  params: SkillMutation;
};


export type MutationCreateSkillArgs = {
  relativePath: Scalars['String']['input'];
  params: SkillMutation;
};


export type MutationUpdateHobbyArgs = {
  relativePath: Scalars['String']['input'];
  params: HobbyMutation;
};


export type MutationCreateHobbyArgs = {
  relativePath: Scalars['String']['input'];
  params: HobbyMutation;
};


export type MutationUpdateDeclarationArgs = {
  relativePath: Scalars['String']['input'];
  params: DeclarationMutation;
};


export type MutationCreateDeclarationArgs = {
  relativePath: Scalars['String']['input'];
  params: DeclarationMutation;
};

export type DocumentUpdateMutation = {
  profile?: InputMaybe<ProfileMutation>;
  experience?: InputMaybe<ExperienceMutation>;
  education?: InputMaybe<EducationMutation>;
  skill?: InputMaybe<SkillMutation>;
  hobby?: InputMaybe<HobbyMutation>;
  declaration?: InputMaybe<DeclarationMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  profile?: InputMaybe<ProfileMutation>;
  experience?: InputMaybe<ExperienceMutation>;
  education?: InputMaybe<EducationMutation>;
  skill?: InputMaybe<SkillMutation>;
  hobby?: InputMaybe<HobbyMutation>;
  declaration?: InputMaybe<DeclarationMutation>;
};

export type ProfileMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
};

export type ExperienceMutation = {
  role?: InputMaybe<Scalars['String']['input']>;
  company?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type EducationMutation = {
  degree?: InputMaybe<Scalars['String']['input']>;
  institution?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type SkillMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
};

export type HobbyMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
};

export type DeclarationMutation = {
  statement?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
};

export type ProfilePartsFragment = { __typename: 'Profile', name: string, role: string, summary?: string | null, email?: string | null, phone?: string | null, image?: string | null };

export type ExperiencePartsFragment = { __typename: 'Experience', role: string, company: string, duration?: string | null, description?: Array<string | null> | null, order?: number | null };

export type EducationPartsFragment = { __typename: 'Education', degree: string, institution: string, status?: string | null, year?: string | null, order?: number | null };

export type SkillPartsFragment = { __typename: 'Skill', title: string, category?: string | null };

export type HobbyPartsFragment = { __typename: 'Hobby', name: string, icon?: string | null };

export type DeclarationPartsFragment = { __typename: 'Declaration', statement?: string | null, name?: string | null };

export type ProfileQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProfileQuery = { __typename?: 'Query', profile: { __typename: 'Profile', id: string, name: string, role: string, summary?: string | null, email?: string | null, phone?: string | null, image?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProfileConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProfileFilter>;
}>;


export type ProfileConnectionQuery = { __typename?: 'Query', profileConnection: { __typename?: 'ProfileConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProfileConnectionEdges', cursor: string, node?: { __typename: 'Profile', id: string, name: string, role: string, summary?: string | null, email?: string | null, phone?: string | null, image?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ExperienceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ExperienceQuery = { __typename?: 'Query', experience: { __typename: 'Experience', id: string, role: string, company: string, duration?: string | null, description?: Array<string | null> | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ExperienceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ExperienceFilter>;
}>;


export type ExperienceConnectionQuery = { __typename?: 'Query', experienceConnection: { __typename?: 'ExperienceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ExperienceConnectionEdges', cursor: string, node?: { __typename: 'Experience', id: string, role: string, company: string, duration?: string | null, description?: Array<string | null> | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type EducationQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EducationQuery = { __typename?: 'Query', education: { __typename: 'Education', id: string, degree: string, institution: string, status?: string | null, year?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EducationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EducationFilter>;
}>;


export type EducationConnectionQuery = { __typename?: 'Query', educationConnection: { __typename?: 'EducationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EducationConnectionEdges', cursor: string, node?: { __typename: 'Education', id: string, degree: string, institution: string, status?: string | null, year?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SkillQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SkillQuery = { __typename?: 'Query', skill: { __typename: 'Skill', id: string, title: string, category?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SkillConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SkillFilter>;
}>;


export type SkillConnectionQuery = { __typename?: 'Query', skillConnection: { __typename?: 'SkillConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SkillConnectionEdges', cursor: string, node?: { __typename: 'Skill', id: string, title: string, category?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HobbyQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HobbyQuery = { __typename?: 'Query', hobby: { __typename: 'Hobby', id: string, name: string, icon?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HobbyConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HobbyFilter>;
}>;


export type HobbyConnectionQuery = { __typename?: 'Query', hobbyConnection: { __typename?: 'HobbyConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HobbyConnectionEdges', cursor: string, node?: { __typename: 'Hobby', id: string, name: string, icon?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type DeclarationQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DeclarationQuery = { __typename?: 'Query', declaration: { __typename: 'Declaration', id: string, statement?: string | null, name?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type DeclarationConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DeclarationFilter>;
}>;


export type DeclarationConnectionQuery = { __typename?: 'Query', declarationConnection: { __typename?: 'DeclarationConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DeclarationConnectionEdges', cursor: string, node?: { __typename: 'Declaration', id: string, statement?: string | null, name?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ProfilePartsFragmentDoc = gql`
    fragment ProfileParts on Profile {
  __typename
  name
  role
  summary
  email
  phone
  image
}
    `;
export const ExperiencePartsFragmentDoc = gql`
    fragment ExperienceParts on Experience {
  __typename
  role
  company
  duration
  description
  order
}
    `;
export const EducationPartsFragmentDoc = gql`
    fragment EducationParts on Education {
  __typename
  degree
  institution
  status
  year
  order
}
    `;
export const SkillPartsFragmentDoc = gql`
    fragment SkillParts on Skill {
  __typename
  title
  category
}
    `;
export const HobbyPartsFragmentDoc = gql`
    fragment HobbyParts on Hobby {
  __typename
  name
  icon
}
    `;
export const DeclarationPartsFragmentDoc = gql`
    fragment DeclarationParts on Declaration {
  __typename
  statement
  name
}
    `;
export const ProfileDocument = gql`
    query profile($relativePath: String!) {
  profile(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProfileParts
  }
}
    ${ProfilePartsFragmentDoc}`;
export const ProfileConnectionDocument = gql`
    query profileConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProfileFilter) {
  profileConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProfileParts
      }
    }
  }
}
    ${ProfilePartsFragmentDoc}`;
export const ExperienceDocument = gql`
    query experience($relativePath: String!) {
  experience(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ExperienceParts
  }
}
    ${ExperiencePartsFragmentDoc}`;
export const ExperienceConnectionDocument = gql`
    query experienceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ExperienceFilter) {
  experienceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ExperienceParts
      }
    }
  }
}
    ${ExperiencePartsFragmentDoc}`;
export const EducationDocument = gql`
    query education($relativePath: String!) {
  education(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EducationParts
  }
}
    ${EducationPartsFragmentDoc}`;
export const EducationConnectionDocument = gql`
    query educationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EducationFilter) {
  educationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EducationParts
      }
    }
  }
}
    ${EducationPartsFragmentDoc}`;
export const SkillDocument = gql`
    query skill($relativePath: String!) {
  skill(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SkillParts
  }
}
    ${SkillPartsFragmentDoc}`;
export const SkillConnectionDocument = gql`
    query skillConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SkillFilter) {
  skillConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SkillParts
      }
    }
  }
}
    ${SkillPartsFragmentDoc}`;
export const HobbyDocument = gql`
    query hobby($relativePath: String!) {
  hobby(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HobbyParts
  }
}
    ${HobbyPartsFragmentDoc}`;
export const HobbyConnectionDocument = gql`
    query hobbyConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HobbyFilter) {
  hobbyConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HobbyParts
      }
    }
  }
}
    ${HobbyPartsFragmentDoc}`;
export const DeclarationDocument = gql`
    query declaration($relativePath: String!) {
  declaration(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DeclarationParts
  }
}
    ${DeclarationPartsFragmentDoc}`;
export const DeclarationConnectionDocument = gql`
    query declarationConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DeclarationFilter) {
  declarationConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DeclarationParts
      }
    }
  }
}
    ${DeclarationPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      profile(variables: ProfileQueryVariables, options?: C): Promise<{data: ProfileQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProfileQueryVariables, query: string}> {
        return requester<{data: ProfileQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProfileQueryVariables, query: string}, ProfileQueryVariables>(ProfileDocument, variables, options);
      },
    profileConnection(variables?: ProfileConnectionQueryVariables, options?: C): Promise<{data: ProfileConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProfileConnectionQueryVariables, query: string}> {
        return requester<{data: ProfileConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProfileConnectionQueryVariables, query: string}, ProfileConnectionQueryVariables>(ProfileConnectionDocument, variables, options);
      },
    experience(variables: ExperienceQueryVariables, options?: C): Promise<{data: ExperienceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExperienceQueryVariables, query: string}> {
        return requester<{data: ExperienceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExperienceQueryVariables, query: string}, ExperienceQueryVariables>(ExperienceDocument, variables, options);
      },
    experienceConnection(variables?: ExperienceConnectionQueryVariables, options?: C): Promise<{data: ExperienceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExperienceConnectionQueryVariables, query: string}> {
        return requester<{data: ExperienceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExperienceConnectionQueryVariables, query: string}, ExperienceConnectionQueryVariables>(ExperienceConnectionDocument, variables, options);
      },
    education(variables: EducationQueryVariables, options?: C): Promise<{data: EducationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EducationQueryVariables, query: string}> {
        return requester<{data: EducationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EducationQueryVariables, query: string}, EducationQueryVariables>(EducationDocument, variables, options);
      },
    educationConnection(variables?: EducationConnectionQueryVariables, options?: C): Promise<{data: EducationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EducationConnectionQueryVariables, query: string}> {
        return requester<{data: EducationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EducationConnectionQueryVariables, query: string}, EducationConnectionQueryVariables>(EducationConnectionDocument, variables, options);
      },
    skill(variables: SkillQueryVariables, options?: C): Promise<{data: SkillQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillQueryVariables, query: string}> {
        return requester<{data: SkillQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillQueryVariables, query: string}, SkillQueryVariables>(SkillDocument, variables, options);
      },
    skillConnection(variables?: SkillConnectionQueryVariables, options?: C): Promise<{data: SkillConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillConnectionQueryVariables, query: string}> {
        return requester<{data: SkillConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SkillConnectionQueryVariables, query: string}, SkillConnectionQueryVariables>(SkillConnectionDocument, variables, options);
      },
    hobby(variables: HobbyQueryVariables, options?: C): Promise<{data: HobbyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HobbyQueryVariables, query: string}> {
        return requester<{data: HobbyQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HobbyQueryVariables, query: string}, HobbyQueryVariables>(HobbyDocument, variables, options);
      },
    hobbyConnection(variables?: HobbyConnectionQueryVariables, options?: C): Promise<{data: HobbyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HobbyConnectionQueryVariables, query: string}> {
        return requester<{data: HobbyConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HobbyConnectionQueryVariables, query: string}, HobbyConnectionQueryVariables>(HobbyConnectionDocument, variables, options);
      },
    declaration(variables: DeclarationQueryVariables, options?: C): Promise<{data: DeclarationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DeclarationQueryVariables, query: string}> {
        return requester<{data: DeclarationQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DeclarationQueryVariables, query: string}, DeclarationQueryVariables>(DeclarationDocument, variables, options);
      },
    declarationConnection(variables?: DeclarationConnectionQueryVariables, options?: C): Promise<{data: DeclarationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DeclarationConnectionQueryVariables, query: string}> {
        return requester<{data: DeclarationConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DeclarationConnectionQueryVariables, query: string}, DeclarationConnectionQueryVariables>(DeclarationConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  